name: Automerge dependabot
on:
  # push:
  #   branches:
  #     - main
  pull_request:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      # - name: Github Action Merge Dependabot
      #   uses: fastify/github-action-merge-dependabot@v3.11.2
      #   with:
      #     use-github-auto-merge: true
      #     target: minor
      #     target-indirect: major
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger auto-merge
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
